/* 회원가입
 */
package Login;

import Profile.ProfileService;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 영
 */
public class Register extends javax.swing.JFrame {
    /**
     * Creates new form Registe
     */
    private File file;
    
    public Register() {
        initComponents();
    }
    
    public String getRegister() {
        String status = "";
        
        if(!password.getText().equals(confirm_password.getText())) {
            confirm_password.setText("");
            confirm_password.requestFocus();
            return "pm";
        } else {
            User user = User.builder()
            .username(user_name.getText())
            .password(password.getText())
            .firstName(first_name.getText())
            .lastName(last_name.getText())
            .phoneNumber(phone_number.getText())
            .eMail(e_mail.getText())
            .build();
        
            UserService service = new UserService(user);
            
            try {
                status = service.sendPost("http://localhost:8080/users");
            } catch (Exception ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return status;
    }
    
    public String checkValue() {
        if (first_name.getText().equals("Enter Your First Name") || first_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your First Name");
            first_name.setText("");
            first_name.requestFocus();
            return "fail";
        }
        if (last_name.getText().equals("Enter Your Last Name") || last_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Last Name");
            last_name.setText("");
            last_name.requestFocus();
            return "fail";
        }
        if (user_name.getText().equals("Enter your Username") || user_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter your Username");
            user_name.setText("");
            user_name.requestFocus();
            return "fail";
        }
        if (phone_number.getText().equals("Enter Your Phone Number") || phone_number.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Phone Number");
            phone_number.setText("");
            phone_number.requestFocus();
            return "fail";
        }
        if (password.getText().equals("jPasswordField1") || password.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Password");
            password.setText("");
            password.requestFocus();
            return "fail";
        }
        if (e_mail.getText().equals("Enter Your E-mail") || e_mail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your E-mail");
            e_mail.setText("");
            e_mail.requestFocus();
            return "fail";
        }
        return "ok";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BackLg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        confirm_password = new javax.swing.JPasswordField();
        user_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        joinIn1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        joinIn2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        e_mail = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phone_number = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        profile = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(65, 65, 85));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 180, 208));
        jLabel3.setText("Register");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 50));

        BackLg.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BackLg.setForeground(new java.awt.Color(150, 180, 208));
        BackLg.setText("Already have an account?");
        BackLg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLgMouseClicked(evt);
            }
        });
        jPanel3.add(BackLg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 250, 40));

        jSeparator2.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator2.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 250, 10));

        jSeparator4.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator4.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 10));

        confirm_password.setBackground(new java.awt.Color(65, 65, 85));
        confirm_password.setForeground(new java.awt.Color(204, 204, 204));
        confirm_password.setText("jPasswordField1");
        confirm_password.setBorder(null);
        confirm_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirm_passwordFocusGained(evt);
            }
        });
        jPanel3.add(confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 250, 30));

        user_name.setBackground(new java.awt.Color(65, 65, 85));
        user_name.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        user_name.setForeground(new java.awt.Color(204, 204, 204));
        user_name.setText("Enter your Username");
        user_name.setBorder(null);
        user_name.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        user_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_nameMouseClicked(evt);
            }
        });
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel3.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(150, 180, 208));
        jLabel11.setText("E-Mail");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 170, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(150, 180, 208));
        jLabel6.setText("Username");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 40));

        jSeparator5.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator5.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 250, 10));

        joinIn1.setBackground(new java.awt.Color(245, 246, 228));
        joinIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinIn1MouseClicked(evt);
            }
        });
        joinIn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(150, 180, 208));
        jLabel10.setText("Sign In");
        joinIn1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 70, 40));

        joinIn2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        joinIn2.setForeground(new java.awt.Color(150, 180, 208));
        joinIn2.setText("create account");
        joinIn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinIn2MouseClicked(evt);
            }
        });
        joinIn1.add(joinIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 40));

        jPanel3.add(joinIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 250, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(150, 180, 208));
        jLabel7.setText("Profile Picture");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 130, 40));

        last_name.setBackground(new java.awt.Color(65, 65, 85));
        last_name.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        last_name.setForeground(new java.awt.Color(204, 204, 204));
        last_name.setText("Enter Your Last Name");
        last_name.setBorder(null);
        last_name.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        last_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                last_nameMouseClicked(evt);
            }
        });
        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });
        jPanel3.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 160, 30));

        jSeparator6.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator6.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 10));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(150, 180, 208));
        jLabel12.setText("First Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 40));

        e_mail.setBackground(new java.awt.Color(65, 65, 85));
        e_mail.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        e_mail.setForeground(new java.awt.Color(204, 204, 204));
        e_mail.setText("Enter Your E-mail");
        e_mail.setBorder(null);
        e_mail.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        e_mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e_mailMouseClicked(evt);
            }
        });
        e_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_mailActionPerformed(evt);
            }
        });
        jPanel3.add(e_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 190, 30));

        jSeparator7.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator7.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 10));

        jSeparator8.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator8.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 250, 10));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(150, 180, 208));
        jLabel13.setText("Confirm Password");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 170, 40));

        first_name.setBackground(new java.awt.Color(65, 65, 85));
        first_name.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        first_name.setForeground(new java.awt.Color(204, 204, 204));
        first_name.setText("Enter Your First Name");
        first_name.setBorder(null);
        first_name.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        first_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                first_nameMouseClicked(evt);
            }
        });
        jPanel3.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(150, 180, 208));
        jLabel14.setText("Phone Number");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 170, 40));

        phone_number.setBackground(new java.awt.Color(65, 65, 85));
        phone_number.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        phone_number.setForeground(new java.awt.Color(204, 204, 204));
        phone_number.setText("Enter Your Phone Number");
        phone_number.setBorder(null);
        phone_number.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        phone_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phone_numberMouseClicked(evt);
            }
        });
        phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numberActionPerformed(evt);
            }
        });
        jPanel3.add(phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, 30));

        jSeparator9.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator9.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 220, 10));

        jSeparator10.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator10.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 250, 10));

        password.setBackground(new java.awt.Color(65, 65, 85));
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("jPasswordField1");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(150, 180, 208));
        jLabel15.setText("Password");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 40));

        jCheckBox3.setBackground(new java.awt.Color(65, 65, 85));
        jCheckBox3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("I agree to the terms and conditions for use");
        jPanel3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, 40));

        jCheckBox4.setBackground(new java.awt.Color(65, 65, 85));
        jCheckBox4.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox4.setSelected(true);
        jCheckBox4.setText("I agree a privacy policy");
        jPanel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 290, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(150, 180, 208));
        jLabel9.setText("Last Name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 170, 40));

        jButton1.setText("upload");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, -1));

        profile.setText("profile");
        jPanel3.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 270, 170));

        jPanel1.setBackground(new java.awt.Color(245, 246, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 180, 208));
        jLabel2.setText("Daily Scheduler");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 290, 60));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(150, 180, 208));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 210));

        jSeparator1.setForeground(new java.awt.Color(150, 180, 208));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 190, 10));

        jSeparator3.setForeground(new java.awt.Color(150, 180, 208));
        jSeparator3.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 230, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_passwordFocusGained
        // TODO add your handling code here:
        confirm_password.setText("");
    }//GEN-LAST:event_confirm_passwordFocusGained

    private void user_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseClicked
        // TODO add your handling code here:
        user_name.setText("");
    }//GEN-LAST:event_user_nameMouseClicked

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_user_nameActionPerformed

    private void last_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_last_nameMouseClicked
        // TODO add your handling code here:
        last_name.setText("");
    }//GEN-LAST:event_last_nameMouseClicked

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_last_nameActionPerformed

    private void e_mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e_mailMouseClicked
        // TODO add your handling code here:
        e_mail.setText("");
    }//GEN-LAST:event_e_mailMouseClicked

    private void e_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_mailActionPerformed

    private void first_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_first_nameMouseClicked
        // TODO add your handling code here:
        first_name.setText("");  
    }//GEN-LAST:event_first_nameMouseClicked

    private void phone_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone_numberMouseClicked
        // TODO add your handling code here:
        phone_number.setText("");    
    }//GEN-LAST:event_phone_numberMouseClicked

    private void phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_numberActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_phone_numberActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:      
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void BackLgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLgMouseClicked
        // TODO add your handling code here:
        LogIn lg = new LogIn();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackLgMouseClicked

    private void joinIn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinIn2MouseClicked
         // TODO add your handling code here:
        String status = checkValue();
        
        if (status.equals("ok")) {
            status = getRegister();
            if (status.contains("ok")) {
                ProfileService service = new ProfileService(file);
                try {
                    service.sendMultiPart(user_name.getText());
                } catch (Exception ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                LogIn lg = new LogIn();
                lg.setVisible(true);
                lg.pack();
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            } else if (status.equals("pm")) {
                JOptionPane.showMessageDialog(null, "Password Mismatch");
            } else {
                JOptionPane.showMessageDialog(null, "Join Failed");
            }
        }
    }//GEN-LAST:event_joinIn2MouseClicked

    private void joinIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinIn1MouseClicked
        // TODO add your handling code here:
        String status = checkValue();
        
        if (status.equals("ok")) {
            status = getRegister();
            if (status.contains("ok")) {
                ProfileService service = new ProfileService(file);
                try {
                    service.sendMultiPart(user_name.getText());
                } catch (Exception ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                LogIn lg = new LogIn();
                lg.setVisible(true);
                lg.pack();
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            } else if (status.equals("pm")) {
                JOptionPane.showMessageDialog(null, "Password Mismatch");
            } else {
                JOptionPane.showMessageDialog(null, "Join Failed");
            }
        }
    }//GEN-LAST:event_joinIn1MouseClicked
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        file = f;
        
        //txt_filename.setText(filename);
        Image getAbsoluteFath = null;
        ImageIcon icon = new ImageIcon(filename);
        
       // image = icon.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), profile.SCALE_SMOOTH);
        profile.setIcon(icon);
        
        
    }//GEN-LAST:event_jButton1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLg;
    private javax.swing.JPasswordField confirm_password;
    private javax.swing.JTextField e_mail;
    private javax.swing.JTextField first_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel joinIn1;
    private javax.swing.JLabel joinIn2;
    private javax.swing.JTextField last_name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone_number;
    private javax.swing.JLabel profile;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}